# Generated by Django 4.0.3 on 2022-04-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('time_span', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('table_num', models.IntegerField()),
                ('selected_num', models.IntegerField()),
            ],
        ),
    ]
