# Generated by Django 4.0.3 on 2022-04-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GraphBot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('val1', models.FloatField()),
                ('val2', models.FloatField()),
                ('average', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
    ]
