# Generated by Django 4.0.3 on 2022-04-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GraphBot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('time_span', models.TimeField()),
                ('name', models.BigIntegerField()),
                ('table_num', models.IntegerField()),
                ('selected_num', models.IntegerField()),
            ],
        ),
    ]
