# Generated by Django 4.0.3 on 2022-04-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GraphBot', '0002_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='val1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='val2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
